#! /usr/bin/env bash

uri=$1

if [ -z "$uri" ]; then
    echo "Usage: open-deep-link <uri>"

    exit 1
fi

adb shell am start \
    -W -a android.intent.action.VIEW \
    -d "$uri" com.sindrenm.templates.project
